/*
 * All-Time World Cup Simulator — Player Database
 *
 * A curated roster of soccer legends spanning the 1950s to the 2020s.
 * Each player has a `pwr` (0-100) representing their effectiveness in their
 * primary role; the match engine reads this when computing line strengths.
 *
 * pos: GK | DEF | MID | FWD
 * pwr: role power used by the engine
 * ovr: overall rating, shown to the player
 *
 * The dataset is deep enough that each of the major footballing nations and
 * each well-populated decade can field a full 4-3-3 (see js/modes.js, which
 * only ever offers options that can actually field a team).
 *
 * To extend the game, just add entries here. Reference an `id` in js/slots.js
 * to add it to an all-time draft tier; decade/nation modes pick it up
 * automatically from its `pos`, `decade` and `nation`.
 */
window.PLAYERS = [
  // ============================ Goalkeepers ============================
  { id: "yashin",       name: "Lev Yashin",        pos: "GK",  nation: "USSR",        flag: "🇷🇺", decade: "1960s", club: "Dynamo Moscow",   ovr: 89, pwr: 90 },
  { id: "banks",        name: "Gordon Banks",      pos: "GK",  nation: "England",     flag: "🏴",  decade: "1960s", club: "Stoke City",      ovr: 87, pwr: 88 },
  { id: "zoff",         name: "Dino Zoff",         pos: "GK",  nation: "Italy",       flag: "🇮🇹", decade: "1970s", club: "Juventus",        ovr: 88, pwr: 89 },
  { id: "maier",        name: "Sepp Maier",        pos: "GK",  nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "Bayern Munich",   ovr: 85, pwr: 86 },
  { id: "fillol",       name: "Ubaldo Fillol",     pos: "GK",  nation: "Argentina",   flag: "🇦🇷", decade: "1970s", club: "River Plate",     ovr: 84, pwr: 85 },
  { id: "shilton",      name: "Peter Shilton",     pos: "GK",  nation: "England",     flag: "🏴",  decade: "1980s", club: "Nott'm Forest",   ovr: 86, pwr: 87 },
  { id: "vanbreukelen", name: "Hans van Breukelen",pos: "GK",  nation: "Netherlands", flag: "🇳🇱", decade: "1980s", club: "PSV Eindhoven",   ovr: 82, pwr: 83 },
  { id: "schmeichel",   name: "Peter Schmeichel",  pos: "GK",  nation: "Denmark",     flag: "🇩🇰", decade: "1990s", club: "Man United",      ovr: 88, pwr: 89 },
  { id: "taffarel",     name: "Cláudio Taffarel",  pos: "GK",  nation: "Brazil",      flag: "🇧🇷", decade: "1990s", club: "Parma",           ovr: 82, pwr: 83 },
  { id: "zubizarreta",  name: "Andoni Zubizarreta",pos: "GK",  nation: "Spain",       flag: "🇪🇸", decade: "1990s", club: "Barcelona",       ovr: 85, pwr: 86 },
  { id: "barthez",      name: "Fabien Barthez",    pos: "GK",  nation: "France",      flag: "🇫🇷", decade: "1990s", club: "AS Monaco",       ovr: 83, pwr: 84 },
  { id: "seaman",       name: "David Seaman",      pos: "GK",  nation: "England",     flag: "🏴",  decade: "1990s", club: "Arsenal",         ovr: 84, pwr: 85 },
  { id: "buffon",       name: "Gianluigi Buffon",  pos: "GK",  nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "Juventus",        ovr: 90, pwr: 91 },
  { id: "casillas",     name: "Iker Casillas",     pos: "GK",  nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Real Madrid",     ovr: 89, pwr: 90 },
  { id: "kahn",         name: "Oliver Kahn",       pos: "GK",  nation: "Germany",     flag: "🇩🇪", decade: "2000s", club: "Bayern Munich",   ovr: 89, pwr: 90 },
  { id: "vandersar",    name: "Edwin van der Sar", pos: "GK",  nation: "Netherlands", flag: "🇳🇱", decade: "2000s", club: "Man United",      ovr: 87, pwr: 88 },
  { id: "neuer",        name: "Manuel Neuer",      pos: "GK",  nation: "Germany",     flag: "🇩🇪", decade: "2010s", club: "Bayern Munich",   ovr: 90, pwr: 91 },
  { id: "lloris",       name: "Hugo Lloris",       pos: "GK",  nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Tottenham",       ovr: 84, pwr: 85 },
  { id: "alisson",      name: "Alisson Becker",    pos: "GK",  nation: "Brazil",      flag: "🇧🇷", decade: "2020s", club: "Liverpool",       ovr: 89, pwr: 90 },
  { id: "emartinez",    name: "Emiliano Martínez", pos: "GK",  nation: "Argentina",   flag: "🇦🇷", decade: "2020s", club: "Aston Villa",     ovr: 85, pwr: 86 },

  // ============================ Defenders ============================
  { id: "djalma",       name: "Djalma Santos",     pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "1960s", club: "Palmeiras",       ovr: 84, pwr: 84 },
  { id: "schnellinger", name: "Karl-Heinz Schnellinger", pos: "DEF", nation: "Germany", flag: "🇩🇪", decade: "1960s", club: "AC Milan",     ovr: 82, pwr: 82 },
  { id: "burgnich",     name: "Tarcisio Burgnich", pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1960s", club: "Inter Milan",     ovr: 82, pwr: 82 },
  { id: "moore",        name: "Bobby Moore",       pos: "DEF", nation: "England",     flag: "🏴",  decade: "1960s", club: "West Ham",        ovr: 88, pwr: 89 },
  { id: "facchetti",    name: "Giacinto Facchetti",pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1960s", club: "Inter Milan",     ovr: 86, pwr: 86 },
  { id: "beckenbauer",  name: "Franz Beckenbauer", pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "Bayern Munich",   ovr: 92, pwr: 90 },
  { id: "passarella",   name: "Daniel Passarella", pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "1970s", club: "River Plate",     ovr: 86, pwr: 85 },
  { id: "vogts",        name: "Berti Vogts",       pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "M'gladbach",      ovr: 84, pwr: 84 },
  { id: "carlosalberto",name: "Carlos Alberto",    pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "1970s", club: "Santos",          ovr: 86, pwr: 86 },
  { id: "krol",         name: "Ruud Krol",         pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "1970s", club: "Ajax",            ovr: 84, pwr: 84 },
  { id: "baresi",       name: "Franco Baresi",     pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1980s", club: "AC Milan",        ovr: 90, pwr: 91 },
  { id: "ruggeri",      name: "Oscar Ruggeri",     pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "1980s", club: "River Plate",     ovr: 82, pwr: 82 },
  { id: "cabrini",      name: "Antonio Cabrini",   pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1980s", club: "Juventus",        ovr: 83, pwr: 83 },
  { id: "brehme",       name: "Andreas Brehme",    pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1980s", club: "Inter Milan",     ovr: 83, pwr: 83 },
  { id: "maldini",      name: "Paolo Maldini",     pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1990s", club: "AC Milan",        ovr: 91, pwr: 91 },
  { id: "robertocarlos",name: "Roberto Carlos",    pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "1990s", club: "Real Madrid",     ovr: 88, pwr: 86 },
  { id: "thuram",       name: "Lilian Thuram",     pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "Juventus",        ovr: 86, pwr: 87 },
  { id: "desailly",     name: "Marcel Desailly",   pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "AC Milan",        ovr: 85, pwr: 86 },
  { id: "sammer",       name: "Matthias Sammer",   pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1990s", club: "Bor. Dortmund",   ovr: 85, pwr: 85 },
  { id: "kohler",       name: "Jürgen Kohler",     pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1990s", club: "Juventus",        ovr: 83, pwr: 83 },
  { id: "adams",        name: "Tony Adams",        pos: "DEF", nation: "England",     flag: "🏴",  decade: "1990s", club: "Arsenal",         ovr: 84, pwr: 84 },
  { id: "blanc",        name: "Laurent Blanc",     pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "Marseille",       ovr: 84, pwr: 84 },
  { id: "lizarazu",     name: "Bixente Lizarazu",  pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "Bayern Munich",   ovr: 83, pwr: 83 },
  { id: "hierro",       name: "Fernando Hierro",   pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "1990s", club: "Real Madrid",     ovr: 85, pwr: 85 },
  { id: "stam",         name: "Jaap Stam",         pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Man United",      ovr: 85, pwr: 85 },
  { id: "frankdeboer",  name: "Frank de Boer",     pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Ajax",            ovr: 82, pwr: 82 },
  { id: "koeman",       name: "Ronald Koeman",     pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Barcelona",       ovr: 84, pwr: 85 },
  { id: "cafu",         name: "Cafu",              pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "AC Milan",        ovr: 87, pwr: 86 },
  { id: "cannavaro",    name: "Fabio Cannavaro",   pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "Real Madrid",     ovr: 88, pwr: 89 },
  { id: "puyol",        name: "Carles Puyol",      pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Barcelona",       ovr: 87, pwr: 88 },
  { id: "nesta",        name: "Alessandro Nesta",  pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "AC Milan",        ovr: 88, pwr: 88 },
  { id: "terry",        name: "John Terry",        pos: "DEF", nation: "England",     flag: "🏴",  decade: "2000s", club: "Chelsea",         ovr: 85, pwr: 85 },
  { id: "ferdinand",    name: "Rio Ferdinand",     pos: "DEF", nation: "England",     flag: "🏴",  decade: "2000s", club: "Man United",      ovr: 85, pwr: 85 },
  { id: "ashleycole",   name: "Ashley Cole",       pos: "DEF", nation: "England",     flag: "🏴",  decade: "2000s", club: "Chelsea",         ovr: 84, pwr: 84 },
  { id: "ayala",        name: "Roberto Ayala",     pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "2000s", club: "Valencia",        ovr: 84, pwr: 84 },
  { id: "zanetti",      name: "Javier Zanetti",    pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "2000s", club: "Inter Milan",     ovr: 85, pwr: 85 },
  { id: "lucio",        name: "Lúcio",             pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "Inter Milan",     ovr: 84, pwr: 84 },
  { id: "sagnol",       name: "Willy Sagnol",      pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Bayern Munich",   ovr: 80, pwr: 80 },
  { id: "lahm",         name: "Philipp Lahm",      pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "2010s", club: "Bayern Munich",   ovr: 88, pwr: 87 },
  { id: "ramos",        name: "Sergio Ramos",      pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Real Madrid",     ovr: 88, pwr: 88 },
  { id: "vandijk",      name: "Virgil van Dijk",   pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "2010s", club: "Liverpool",       ovr: 89, pwr: 89 },
  { id: "hummels",      name: "Mats Hummels",      pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "2010s", club: "Bayern Munich",   ovr: 85, pwr: 85 },
  { id: "thiagosilva",  name: "Thiago Silva",      pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "2010s", club: "PSG",             ovr: 86, pwr: 86 },
  { id: "marcelo",      name: "Marcelo",           pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "2010s", club: "Real Madrid",     ovr: 83, pwr: 83 },
  { id: "varane",       name: "Raphaël Varane",    pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Real Madrid",     ovr: 84, pwr: 84 },
  { id: "pique",        name: "Gerard Piqué",      pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 85, pwr: 85 },
  { id: "carvajal",     name: "Dani Carvajal",     pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Real Madrid",     ovr: 82, pwr: 82 },
  { id: "otamendi",     name: "Nicolás Otamendi",  pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "2020s", club: "Benfica",         ovr: 81, pwr: 81 },

  // ============================ Midfielders ============================
  { id: "bobbycharlton",name: "Bobby Charlton",    pos: "MID", nation: "England",     flag: "🏴",  decade: "1960s", club: "Man United",      ovr: 89, pwr: 88 },
  { id: "didi",         name: "Didi",              pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "1960s", club: "Botafogo",        ovr: 85, pwr: 85 },
  { id: "suarez_l",     name: "Luis Suárez",       pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "1960s", club: "Inter Milan",     ovr: 84, pwr: 84 },
  { id: "platini",      name: "Michel Platini",    pos: "MID", nation: "France",      flag: "🇫🇷", decade: "1980s", club: "Juventus",        ovr: 90, pwr: 89 },
  { id: "rivera",       name: "Gianni Rivera",     pos: "MID", nation: "Italy",       flag: "🇮🇹", decade: "1970s", club: "AC Milan",        ovr: 85, pwr: 85 },
  { id: "gerson",       name: "Gérson",            pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "1970s", club: "Botafogo",        ovr: 84, pwr: 84 },
  { id: "netzer",       name: "Günter Netzer",     pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "M'gladbach",      ovr: 84, pwr: 84 },
  { id: "overath",      name: "Wolfgang Overath",  pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "FC Köln",         ovr: 82, pwr: 82 },
  { id: "neeskens",     name: "Johan Neeskens",    pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "1970s", club: "Ajax",            ovr: 84, pwr: 84 },
  { id: "zico",         name: "Zico",              pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "1980s", club: "Flamengo",        ovr: 89, pwr: 88 },
  { id: "socrates",     name: "Sócrates",          pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "1980s", club: "Corinthians",     ovr: 86, pwr: 86 },
  { id: "gullit",       name: "Ruud Gullit",       pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "1980s", club: "AC Milan",        ovr: 88, pwr: 87 },
  { id: "matthaus",     name: "Lothar Matthäus",   pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "1990s", club: "Inter Milan",     ovr: 89, pwr: 88 },
  { id: "baggio",       name: "Roberto Baggio",    pos: "MID", nation: "Italy",       flag: "🇮🇹", decade: "1990s", club: "Juventus",        ovr: 88, pwr: 87 },
  { id: "redondo",      name: "Fernando Redondo",  pos: "MID", nation: "Argentina",   flag: "🇦🇷", decade: "1990s", club: "Real Madrid",     ovr: 85, pwr: 85 },
  { id: "rijkaard",     name: "Frank Rijkaard",    pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "AC Milan",        ovr: 86, pwr: 86 },
  { id: "davids",       name: "Edgar Davids",      pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Juventus",        ovr: 83, pwr: 83 },
  { id: "zidane",       name: "Zinedine Zidane",   pos: "MID", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Real Madrid",     ovr: 92, pwr: 92 },
  { id: "pirlo",        name: "Andrea Pirlo",      pos: "MID", nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "AC Milan",        ovr: 88, pwr: 89 },
  { id: "xavi",         name: "Xavi Hernández",    pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Barcelona",       ovr: 89, pwr: 91 },
  { id: "gerrard",      name: "Steven Gerrard",    pos: "MID", nation: "England",     flag: "🏴",  decade: "2000s", club: "Liverpool",       ovr: 87, pwr: 87 },
  { id: "scholes",      name: "Paul Scholes",      pos: "MID", nation: "England",     flag: "🏴",  decade: "2000s", club: "Man United",      ovr: 85, pwr: 86 },
  { id: "riquelme",     name: "Juan Román Riquelme",pos:"MID", nation: "Argentina",   flag: "🇦🇷", decade: "2000s", club: "Villarreal",      ovr: 85, pwr: 86 },
  { id: "kaka",         name: "Kaká",              pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "AC Milan",        ovr: 87, pwr: 87 },
  { id: "rivaldo",      name: "Rivaldo",           pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "Barcelona",       ovr: 87, pwr: 87 },
  { id: "ballack",      name: "Michael Ballack",   pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "2000s", club: "Chelsea",         ovr: 84, pwr: 84 },
  { id: "lampard",      name: "Frank Lampard",     pos: "MID", nation: "England",     flag: "🏴",  decade: "2000s", club: "Chelsea",         ovr: 85, pwr: 85 },
  { id: "beckham",      name: "David Beckham",     pos: "MID", nation: "England",     flag: "🏴",  decade: "2000s", club: "Man United",      ovr: 84, pwr: 84 },
  { id: "veron",        name: "Juan Sebastián Verón",pos:"MID",nation: "Argentina",   flag: "🇦🇷", decade: "2000s", club: "Lazio",           ovr: 83, pwr: 83 },
  { id: "vieira",       name: "Patrick Vieira",    pos: "MID", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Arsenal",         ovr: 85, pwr: 85 },
  { id: "modric",       name: "Luka Modrić",       pos: "MID", nation: "Croatia",     flag: "🇭🇷", decade: "2010s", club: "Real Madrid",     ovr: 89, pwr: 89 },
  { id: "kante",        name: "N'Golo Kanté",      pos: "MID", nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Chelsea",         ovr: 86, pwr: 86 },
  { id: "debruyne",     name: "Kevin De Bruyne",   pos: "MID", nation: "Belgium",     flag: "🇧🇪", decade: "2010s", club: "Man City",        ovr: 89, pwr: 89 },
  { id: "iniesta",      name: "Andrés Iniesta",    pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 90, pwr: 90 },
  { id: "busquets",     name: "Sergio Busquets",   pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 86, pwr: 86 },
  { id: "fabregas",     name: "Cesc Fàbregas",     pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 83, pwr: 83 },
  { id: "kroos",        name: "Toni Kroos",        pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "2010s", club: "Real Madrid",     ovr: 86, pwr: 86 },
  { id: "sneijder",     name: "Wesley Sneijder",   pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "2010s", club: "Inter Milan",     ovr: 84, pwr: 84 },
  { id: "derossi",      name: "Daniele De Rossi",  pos: "MID", nation: "Italy",       flag: "🇮🇹", decade: "2010s", club: "AS Roma",         ovr: 82, pwr: 82 },
  { id: "mascherano",   name: "Javier Mascherano", pos: "MID", nation: "Argentina",   flag: "🇦🇷", decade: "2010s", club: "Barcelona",       ovr: 83, pwr: 83 },
  { id: "depaul",       name: "Rodrigo De Paul",   pos: "MID", nation: "Argentina",   flag: "🇦🇷", decade: "2020s", club: "Atlético Madrid", ovr: 80, pwr: 80 },

  // ============================ Forwards ============================
  { id: "distefano",    name: "Alfredo Di Stéfano",pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "1950s", club: "Real Madrid",     ovr: 91, pwr: 90 },
  { id: "puskas",       name: "Ferenc Puskás",     pos: "FWD", nation: "Hungary",     flag: "🇭🇺", decade: "1950s", club: "Real Madrid",     ovr: 90, pwr: 91 },
  { id: "pele",         name: "Pelé",              pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "1960s", club: "Santos",          ovr: 95, pwr: 95 },
  { id: "eusebio",      name: "Eusébio",           pos: "FWD", nation: "Portugal",    flag: "🇵🇹", decade: "1960s", club: "Benfica",         ovr: 89, pwr: 90 },
  { id: "garrincha",    name: "Garrincha",         pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "1960s", club: "Botafogo",        ovr: 89, pwr: 89 },
  { id: "seeler",       name: "Uwe Seeler",        pos: "FWD", nation: "Germany",     flag: "🇩🇪", decade: "1960s", club: "Hamburg",         ovr: 83, pwr: 84 },
  { id: "greaves",      name: "Jimmy Greaves",     pos: "FWD", nation: "England",     flag: "🏴",  decade: "1960s", club: "Tottenham",       ovr: 84, pwr: 85 },
  { id: "muller",       name: "Gerd Müller",       pos: "FWD", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "Bayern Munich",   ovr: 90, pwr: 92 },
  { id: "cruyff",       name: "Johan Cruyff",      pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "1970s", club: "Ajax",            ovr: 93, pwr: 92 },
  { id: "best",         name: "George Best",       pos: "FWD", nation: "N. Ireland",  flag: "🇬🇧", decade: "1970s", club: "Man United",      ovr: 88, pwr: 88 },
  { id: "riva",         name: "Gigi Riva",         pos: "FWD", nation: "Italy",       flag: "🇮🇹", decade: "1970s", club: "Cagliari",        ovr: 85, pwr: 86 },
  { id: "kempes",       name: "Mario Kempes",      pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "1970s", club: "Valencia",        ovr: 85, pwr: 85 },
  { id: "rivelino",     name: "Rivelino",          pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "1970s", club: "Corinthians",     ovr: 85, pwr: 85 },
  { id: "vanbasten",    name: "Marco van Basten",  pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "1980s", club: "AC Milan",        ovr: 90, pwr: 91 },
  { id: "rummenigge",   name: "Karl-Heinz Rummenigge",pos:"FWD",nation: "Germany",    flag: "🇩🇪", decade: "1980s", club: "Bayern Munich",   ovr: 86, pwr: 87 },
  { id: "rossi",        name: "Paolo Rossi",       pos: "FWD", nation: "Italy",       flag: "🇮🇹", decade: "1980s", club: "Juventus",        ovr: 84, pwr: 85 },
  { id: "butragueno",   name: "Emilio Butragueño", pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "1980s", club: "Real Madrid",     ovr: 82, pwr: 82 },
  { id: "lineker",      name: "Gary Lineker",      pos: "FWD", nation: "England",     flag: "🏴",  decade: "1980s", club: "Tottenham",       ovr: 85, pwr: 85 },
  { id: "maradona",     name: "Diego Maradona",    pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "1980s", club: "Napoli",          ovr: 94, pwr: 93 },
  { id: "romario",      name: "Romário",           pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "1990s", club: "Barcelona",       ovr: 88, pwr: 90 },
  { id: "batistuta",    name: "Gabriel Batistuta", pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "1990s", club: "Fiorentina",      ovr: 86, pwr: 88 },
  { id: "klinsmann",    name: "Jürgen Klinsmann",  pos: "FWD", nation: "Germany",     flag: "🇩🇪", decade: "1990s", club: "Tottenham",       ovr: 85, pwr: 86 },
  { id: "papin",        name: "Jean-Pierre Papin", pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "Marseille",       ovr: 84, pwr: 85 },
  { id: "shearer",      name: "Alan Shearer",      pos: "FWD", nation: "England",     flag: "🏴",  decade: "1990s", club: "Newcastle",       ovr: 85, pwr: 86 },
  { id: "bergkamp",     name: "Dennis Bergkamp",   pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Arsenal",         ovr: 87, pwr: 87 },
  { id: "ronaldo",      name: "Ronaldo Nazário",   pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "Real Madrid",     ovr: 92, pwr: 93 },
  { id: "ronaldinho",   name: "Ronaldinho",        pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "Barcelona",       ovr: 90, pwr: 90 },
  { id: "henry",        name: "Thierry Henry",     pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Arsenal",         ovr: 88, pwr: 89 },
  { id: "trezeguet",    name: "David Trezeguet",   pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Juventus",        ovr: 83, pwr: 84 },
  { id: "klose",        name: "Miroslav Klose",    pos: "FWD", nation: "Germany",     flag: "🇩🇪", decade: "2000s", club: "Bayern Munich",   ovr: 84, pwr: 85 },
  { id: "delpiero",     name: "Alessandro Del Piero",pos:"FWD",nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "Juventus",        ovr: 86, pwr: 86 },
  { id: "totti",        name: "Francesco Totti",   pos: "FWD", nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "AS Roma",         ovr: 86, pwr: 86 },
  { id: "raul",         name: "Raúl",              pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Real Madrid",     ovr: 86, pwr: 86 },
  { id: "torres",       name: "Fernando Torres",   pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Liverpool",       ovr: 84, pwr: 84 },
  { id: "morientes",    name: "Fernando Morientes",pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Real Madrid",     ovr: 81, pwr: 81 },
  { id: "owen",         name: "Michael Owen",      pos: "FWD", nation: "England",     flag: "🏴",  decade: "2000s", club: "Liverpool",       ovr: 83, pwr: 84 },
  { id: "vannistelrooy",name: "Ruud van Nistelrooy",pos:"FWD", nation: "Netherlands", flag: "🇳🇱", decade: "2000s", club: "Man United",      ovr: 84, pwr: 85 },
  { id: "messi",        name: "Lionel Messi",      pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "2010s", club: "Barcelona",       ovr: 95, pwr: 95 },
  { id: "cristiano",    name: "Cristiano Ronaldo", pos: "FWD", nation: "Portugal",    flag: "🇵🇹", decade: "2010s", club: "Real Madrid",     ovr: 93, pwr: 93 },
  { id: "ibrahimovic",  name: "Zlatan Ibrahimović",pos: "FWD", nation: "Sweden",      flag: "🇸🇪", decade: "2010s", club: "Milan / PSG",     ovr: 88, pwr: 88 },
  { id: "benzema",      name: "Karim Benzema",     pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Real Madrid",     ovr: 86, pwr: 87 },
  { id: "griezmann",    name: "Antoine Griezmann", pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Atlético Madrid", ovr: 84, pwr: 84 },
  { id: "villa",        name: "David Villa",       pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 84, pwr: 85 },
  { id: "rooney",       name: "Wayne Rooney",      pos: "FWD", nation: "England",     flag: "🏴",  decade: "2010s", club: "Man United",      ovr: 85, pwr: 85 },
  { id: "robben",       name: "Arjen Robben",      pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "2010s", club: "Bayern Munich",   ovr: 85, pwr: 85 },
  { id: "vanpersie",    name: "Robin van Persie",  pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "2010s", club: "Man United",      ovr: 84, pwr: 85 },
  { id: "aguero",       name: "Sergio Agüero",     pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "2010s", club: "Man City",        ovr: 85, pwr: 86 },
  { id: "neymar",       name: "Neymar",            pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "2010s", club: "Barcelona / PSG", ovr: 86, pwr: 87 },
  { id: "mbappe",       name: "Kylian Mbappé",     pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2020s", club: "Paris SG",        ovr: 91, pwr: 92 },
  { id: "lewandowski",  name: "Robert Lewandowski",pos: "FWD", nation: "Poland",      flag: "🇵🇱", decade: "2020s", club: "Bayern Munich",   ovr: 90, pwr: 91 },
  { id: "kane",         name: "Harry Kane",        pos: "FWD", nation: "England",     flag: "🏴",  decade: "2020s", club: "Bayern Munich",   ovr: 85, pwr: 86 },
];

// Lookup helper used across the app.
window.PLAYER_BY_ID = window.PLAYERS.reduce(function (acc, p) {
  acc[p.id] = p;
  return acc;
}, {});
