/*
 * Copa XI: All-Time World Cup — Player Database
 *
 * A curated roster of soccer legends spanning the 1950s to the 2020s.
 * Each player has a `pwr` (0-100) representing their effectiveness in their
 * primary role; the match engine reads this when computing line strengths.
 *
 * pos: GK | DEF | MID | FWD
 * pwr: role power used by the engine
 * ovr: overall rating, shown to the player
 *
 * The dataset is deep enough that each of the major footballing nations and
 * each well-populated decade can field a full 4-3-3 (see js/modes.js, which
 * only ever offers options that can actually field a team).
 *
 * To extend the game, just add entries here. Reference an `id` in js/slots.js
 * to add it to an all-time draft tier; decade/nation modes pick it up
 * automatically from its `pos`, `decade` and `nation`.
 */
window.PLAYERS = [
  // ============================ Goalkeepers ============================
  { id: "yashin",       name: "Lev Yashin",        pos: "GK",  nation: "USSR",        flag: "🇷🇺", decade: "1960s", club: "Dynamo Moscow",   ovr: 89, pwr: 90 },
  { id: "banks",        name: "Gordon Banks",      pos: "GK",  nation: "England",     flag: "🏴",  decade: "1960s", club: "Stoke City",      ovr: 87, pwr: 88 },
  { id: "zoff",         name: "Dino Zoff",         pos: "GK",  nation: "Italy",       flag: "🇮🇹", decade: "1970s", club: "Juventus",        ovr: 88, pwr: 89 },
  { id: "maier",        name: "Sepp Maier",        pos: "GK",  nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "Bayern Munich",   ovr: 85, pwr: 86 },
  { id: "fillol",       name: "Ubaldo Fillol",     pos: "GK",  nation: "Argentina",   flag: "🇦🇷", decade: "1970s", club: "River Plate",     ovr: 84, pwr: 85 },
  { id: "shilton",      name: "Peter Shilton",     pos: "GK",  nation: "England",     flag: "🏴",  decade: "1980s", club: "Nott'm Forest",   ovr: 86, pwr: 87 },
  { id: "vanbreukelen", name: "Hans van Breukelen",pos: "GK",  nation: "Netherlands", flag: "🇳🇱", decade: "1980s", club: "PSV Eindhoven",   ovr: 82, pwr: 83 },
  { id: "schmeichel",   name: "Peter Schmeichel",  pos: "GK",  nation: "Denmark",     flag: "🇩🇰", decade: "1990s", club: "Man United",      ovr: 88, pwr: 89 },
  { id: "taffarel",     name: "Cláudio Taffarel",  pos: "GK",  nation: "Brazil",      flag: "🇧🇷", decade: "1990s", club: "Parma",           ovr: 82, pwr: 83 },
  { id: "zubizarreta",  name: "Andoni Zubizarreta",pos: "GK",  nation: "Spain",       flag: "🇪🇸", decade: "1990s", club: "Barcelona",       ovr: 85, pwr: 86 },
  { id: "barthez",      name: "Fabien Barthez",    pos: "GK",  nation: "France",      flag: "🇫🇷", decade: "1990s", club: "AS Monaco",       ovr: 83, pwr: 84 },
  { id: "seaman",       name: "David Seaman",      pos: "GK",  nation: "England",     flag: "🏴",  decade: "1990s", club: "Arsenal",         ovr: 84, pwr: 85 },
  { id: "buffon",       name: "Gianluigi Buffon",  pos: "GK",  nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "Juventus",        ovr: 90, pwr: 91 },
  { id: "casillas",     name: "Iker Casillas",     pos: "GK",  nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Real Madrid",     ovr: 89, pwr: 90 },
  { id: "kahn",         name: "Oliver Kahn",       pos: "GK",  nation: "Germany",     flag: "🇩🇪", decade: "2000s", club: "Bayern Munich",   ovr: 89, pwr: 90 },
  { id: "vandersar",    name: "Edwin van der Sar", pos: "GK",  nation: "Netherlands", flag: "🇳🇱", decade: "2000s", club: "Man United",      ovr: 87, pwr: 88 },
  { id: "neuer",        name: "Manuel Neuer",      pos: "GK",  nation: "Germany",     flag: "🇩🇪", decade: "2010s", club: "Bayern Munich",   ovr: 90, pwr: 91 },
  { id: "lloris",       name: "Hugo Lloris",       pos: "GK",  nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Tottenham",       ovr: 84, pwr: 85 },
  { id: "alisson",      name: "Alisson Becker",    pos: "GK",  nation: "Brazil",      flag: "🇧🇷", decade: "2020s", club: "Liverpool",       ovr: 89, pwr: 90 },
  { id: "emartinez",    name: "Emiliano Martínez", pos: "GK",  nation: "Argentina",   flag: "🇦🇷", decade: "2020s", club: "Aston Villa",     ovr: 85, pwr: 86 },

  // ============================ Defenders ============================
  { id: "djalma",       name: "Djalma Santos",     pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "1960s", club: "Palmeiras",       ovr: 84, pwr: 84 },
  { id: "schnellinger", name: "Karl-Heinz Schnellinger", pos: "DEF", nation: "Germany", flag: "🇩🇪", decade: "1960s", club: "AC Milan",     ovr: 82, pwr: 82 },
  { id: "burgnich",     name: "Tarcisio Burgnich", pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1960s", club: "Inter Milan",     ovr: 82, pwr: 82 },
  { id: "moore",        name: "Bobby Moore",       pos: "DEF", nation: "England",     flag: "🏴",  decade: "1960s", club: "West Ham",        ovr: 88, pwr: 89 },
  { id: "facchetti",    name: "Giacinto Facchetti",pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1960s", club: "Inter Milan",     ovr: 86, pwr: 86 },
  { id: "beckenbauer",  name: "Franz Beckenbauer", pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "Bayern Munich",   ovr: 92, pwr: 90 },
  { id: "passarella",   name: "Daniel Passarella", pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "1970s", club: "River Plate",     ovr: 86, pwr: 85 },
  { id: "vogts",        name: "Berti Vogts",       pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "M'gladbach",      ovr: 84, pwr: 84 },
  { id: "carlosalberto",name: "Carlos Alberto",    pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "1970s", club: "Santos",          ovr: 86, pwr: 86 },
  { id: "krol",         name: "Ruud Krol",         pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "1970s", club: "Ajax",            ovr: 84, pwr: 84 },
  { id: "baresi",       name: "Franco Baresi",     pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1980s", club: "AC Milan",        ovr: 90, pwr: 91 },
  { id: "ruggeri",      name: "Oscar Ruggeri",     pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "1980s", club: "River Plate",     ovr: 82, pwr: 82 },
  { id: "cabrini",      name: "Antonio Cabrini",   pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1980s", club: "Juventus",        ovr: 83, pwr: 83 },
  { id: "brehme",       name: "Andreas Brehme",    pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1980s", club: "Inter Milan",     ovr: 83, pwr: 83 },
  { id: "maldini",      name: "Paolo Maldini",     pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "1990s", club: "AC Milan",        ovr: 91, pwr: 91 },
  { id: "robertocarlos",name: "Roberto Carlos",    pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "1990s", club: "Real Madrid",     ovr: 88, pwr: 86 },
  { id: "thuram",       name: "Lilian Thuram",     pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "Juventus",        ovr: 86, pwr: 87 },
  { id: "desailly",     name: "Marcel Desailly",   pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "AC Milan",        ovr: 85, pwr: 86 },
  { id: "sammer",       name: "Matthias Sammer",   pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1990s", club: "Bor. Dortmund",   ovr: 85, pwr: 85 },
  { id: "kohler",       name: "Jürgen Kohler",     pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "1990s", club: "Juventus",        ovr: 83, pwr: 83 },
  { id: "adams",        name: "Tony Adams",        pos: "DEF", nation: "England",     flag: "🏴",  decade: "1990s", club: "Arsenal",         ovr: 84, pwr: 84 },
  { id: "blanc",        name: "Laurent Blanc",     pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "Marseille",       ovr: 84, pwr: 84 },
  { id: "lizarazu",     name: "Bixente Lizarazu",  pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "Bayern Munich",   ovr: 83, pwr: 83 },
  { id: "hierro",       name: "Fernando Hierro",   pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "1990s", club: "Real Madrid",     ovr: 85, pwr: 85 },
  { id: "stam",         name: "Jaap Stam",         pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Man United",      ovr: 85, pwr: 85 },
  { id: "frankdeboer",  name: "Frank de Boer",     pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Ajax",            ovr: 82, pwr: 82 },
  { id: "koeman",       name: "Ronald Koeman",     pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Barcelona",       ovr: 84, pwr: 85 },
  { id: "cafu",         name: "Cafu",              pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "AC Milan",        ovr: 87, pwr: 86 },
  { id: "cannavaro",    name: "Fabio Cannavaro",   pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "Real Madrid",     ovr: 88, pwr: 89 },
  { id: "puyol",        name: "Carles Puyol",      pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Barcelona",       ovr: 87, pwr: 88 },
  { id: "nesta",        name: "Alessandro Nesta",  pos: "DEF", nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "AC Milan",        ovr: 88, pwr: 88 },
  { id: "terry",        name: "John Terry",        pos: "DEF", nation: "England",     flag: "🏴",  decade: "2000s", club: "Chelsea",         ovr: 85, pwr: 85 },
  { id: "ferdinand",    name: "Rio Ferdinand",     pos: "DEF", nation: "England",     flag: "🏴",  decade: "2000s", club: "Man United",      ovr: 85, pwr: 85 },
  { id: "ashleycole",   name: "Ashley Cole",       pos: "DEF", nation: "England",     flag: "🏴",  decade: "2000s", club: "Chelsea",         ovr: 84, pwr: 84 },
  { id: "ayala",        name: "Roberto Ayala",     pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "2000s", club: "Valencia",        ovr: 84, pwr: 84 },
  { id: "zanetti",      name: "Javier Zanetti",    pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "2000s", club: "Inter Milan",     ovr: 85, pwr: 85 },
  { id: "lucio",        name: "Lúcio",             pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "Inter Milan",     ovr: 84, pwr: 84 },
  { id: "sagnol",       name: "Willy Sagnol",      pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Bayern Munich",   ovr: 80, pwr: 80 },
  { id: "lahm",         name: "Philipp Lahm",      pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "2010s", club: "Bayern Munich",   ovr: 88, pwr: 87 },
  { id: "ramos",        name: "Sergio Ramos",      pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Real Madrid",     ovr: 88, pwr: 88 },
  { id: "vandijk",      name: "Virgil van Dijk",   pos: "DEF", nation: "Netherlands", flag: "🇳🇱", decade: "2010s", club: "Liverpool",       ovr: 89, pwr: 89 },
  { id: "hummels",      name: "Mats Hummels",      pos: "DEF", nation: "Germany",     flag: "🇩🇪", decade: "2010s", club: "Bayern Munich",   ovr: 85, pwr: 85 },
  { id: "thiagosilva",  name: "Thiago Silva",      pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "2010s", club: "PSG",             ovr: 86, pwr: 86 },
  { id: "marcelo",      name: "Marcelo",           pos: "DEF", nation: "Brazil",      flag: "🇧🇷", decade: "2010s", club: "Real Madrid",     ovr: 83, pwr: 83 },
  { id: "varane",       name: "Raphaël Varane",    pos: "DEF", nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Real Madrid",     ovr: 84, pwr: 84 },
  { id: "pique",        name: "Gerard Piqué",      pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 85, pwr: 85 },
  { id: "carvajal",     name: "Dani Carvajal",     pos: "DEF", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Real Madrid",     ovr: 82, pwr: 82 },
  { id: "otamendi",     name: "Nicolás Otamendi",  pos: "DEF", nation: "Argentina",   flag: "🇦🇷", decade: "2020s", club: "Benfica",         ovr: 81, pwr: 81 },

  // ============================ Midfielders ============================
  { id: "bobbycharlton",name: "Bobby Charlton",    pos: "MID", nation: "England",     flag: "🏴",  decade: "1960s", club: "Man United",      ovr: 89, pwr: 88 },
  { id: "didi",         name: "Didi",              pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "1960s", club: "Botafogo",        ovr: 85, pwr: 85 },
  { id: "suarez_l",     name: "Luis Suárez",       pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "1960s", club: "Inter Milan",     ovr: 84, pwr: 84 },
  { id: "platini",      name: "Michel Platini",    pos: "MID", nation: "France",      flag: "🇫🇷", decade: "1980s", club: "Juventus",        ovr: 90, pwr: 89 },
  { id: "rivera",       name: "Gianni Rivera",     pos: "MID", nation: "Italy",       flag: "🇮🇹", decade: "1970s", club: "AC Milan",        ovr: 85, pwr: 85 },
  { id: "gerson",       name: "Gérson",            pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "1970s", club: "Botafogo",        ovr: 84, pwr: 84 },
  { id: "netzer",       name: "Günter Netzer",     pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "M'gladbach",      ovr: 84, pwr: 84 },
  { id: "overath",      name: "Wolfgang Overath",  pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "FC Köln",         ovr: 82, pwr: 82 },
  { id: "neeskens",     name: "Johan Neeskens",    pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "1970s", club: "Ajax",            ovr: 84, pwr: 84 },
  { id: "zico",         name: "Zico",              pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "1980s", club: "Flamengo",        ovr: 89, pwr: 88 },
  { id: "socrates",     name: "Sócrates",          pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "1980s", club: "Corinthians",     ovr: 86, pwr: 86 },
  { id: "gullit",       name: "Ruud Gullit",       pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "1980s", club: "AC Milan",        ovr: 88, pwr: 87 },
  { id: "matthaus",     name: "Lothar Matthäus",   pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "1990s", club: "Inter Milan",     ovr: 89, pwr: 88 },
  { id: "baggio",       name: "Roberto Baggio",    pos: "MID", nation: "Italy",       flag: "🇮🇹", decade: "1990s", club: "Juventus",        ovr: 88, pwr: 87 },
  { id: "redondo",      name: "Fernando Redondo",  pos: "MID", nation: "Argentina",   flag: "🇦🇷", decade: "1990s", club: "Real Madrid",     ovr: 85, pwr: 85 },
  { id: "rijkaard",     name: "Frank Rijkaard",    pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "AC Milan",        ovr: 86, pwr: 86 },
  { id: "davids",       name: "Edgar Davids",      pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Juventus",        ovr: 83, pwr: 83 },
  { id: "zidane",       name: "Zinedine Zidane",   pos: "MID", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Real Madrid",     ovr: 92, pwr: 92 },
  { id: "pirlo",        name: "Andrea Pirlo",      pos: "MID", nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "AC Milan",        ovr: 88, pwr: 89 },
  { id: "xavi",         name: "Xavi Hernández",    pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Barcelona",       ovr: 89, pwr: 91 },
  { id: "gerrard",      name: "Steven Gerrard",    pos: "MID", nation: "England",     flag: "🏴",  decade: "2000s", club: "Liverpool",       ovr: 87, pwr: 87 },
  { id: "scholes",      name: "Paul Scholes",      pos: "MID", nation: "England",     flag: "🏴",  decade: "2000s", club: "Man United",      ovr: 85, pwr: 86 },
  { id: "riquelme",     name: "Juan Román Riquelme",pos:"MID", nation: "Argentina",   flag: "🇦🇷", decade: "2000s", club: "Villarreal",      ovr: 85, pwr: 86 },
  { id: "kaka",         name: "Kaká",              pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "AC Milan",        ovr: 87, pwr: 87 },
  { id: "rivaldo",      name: "Rivaldo",           pos: "MID", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "Barcelona",       ovr: 87, pwr: 87 },
  { id: "ballack",      name: "Michael Ballack",   pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "2000s", club: "Chelsea",         ovr: 84, pwr: 84 },
  { id: "lampard",      name: "Frank Lampard",     pos: "MID", nation: "England",     flag: "🏴",  decade: "2000s", club: "Chelsea",         ovr: 85, pwr: 85 },
  { id: "beckham",      name: "David Beckham",     pos: "MID", nation: "England",     flag: "🏴",  decade: "2000s", club: "Man United",      ovr: 84, pwr: 84 },
  { id: "veron",        name: "Juan Sebastián Verón",pos:"MID",nation: "Argentina",   flag: "🇦🇷", decade: "2000s", club: "Lazio",           ovr: 83, pwr: 83 },
  { id: "vieira",       name: "Patrick Vieira",    pos: "MID", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Arsenal",         ovr: 85, pwr: 85 },
  { id: "modric",       name: "Luka Modrić",       pos: "MID", nation: "Croatia",     flag: "🇭🇷", decade: "2010s", club: "Real Madrid",     ovr: 89, pwr: 89 },
  { id: "kante",        name: "N'Golo Kanté",      pos: "MID", nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Chelsea",         ovr: 86, pwr: 86 },
  { id: "debruyne",     name: "Kevin De Bruyne",   pos: "MID", nation: "Belgium",     flag: "🇧🇪", decade: "2010s", club: "Man City",        ovr: 89, pwr: 89 },
  { id: "iniesta",      name: "Andrés Iniesta",    pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 90, pwr: 90 },
  { id: "busquets",     name: "Sergio Busquets",   pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 86, pwr: 86 },
  { id: "fabregas",     name: "Cesc Fàbregas",     pos: "MID", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 83, pwr: 83 },
  { id: "kroos",        name: "Toni Kroos",        pos: "MID", nation: "Germany",     flag: "🇩🇪", decade: "2010s", club: "Real Madrid",     ovr: 86, pwr: 86 },
  { id: "sneijder",     name: "Wesley Sneijder",   pos: "MID", nation: "Netherlands", flag: "🇳🇱", decade: "2010s", club: "Inter Milan",     ovr: 84, pwr: 84 },
  { id: "derossi",      name: "Daniele De Rossi",  pos: "MID", nation: "Italy",       flag: "🇮🇹", decade: "2010s", club: "AS Roma",         ovr: 82, pwr: 82 },
  { id: "mascherano",   name: "Javier Mascherano", pos: "MID", nation: "Argentina",   flag: "🇦🇷", decade: "2010s", club: "Barcelona",       ovr: 83, pwr: 83 },
  { id: "depaul",       name: "Rodrigo De Paul",   pos: "MID", nation: "Argentina",   flag: "🇦🇷", decade: "2020s", club: "Atlético Madrid", ovr: 80, pwr: 80 },

  // ============================ Forwards ============================
  { id: "distefano",    name: "Alfredo Di Stéfano",pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "1950s", club: "Real Madrid",     ovr: 91, pwr: 90 },
  { id: "puskas",       name: "Ferenc Puskás",     pos: "FWD", nation: "Hungary",     flag: "🇭🇺", decade: "1950s", club: "Real Madrid",     ovr: 90, pwr: 91 },
  { id: "pele",         name: "Pelé",              pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "1960s", club: "Santos",          ovr: 95, pwr: 95 },
  { id: "eusebio",      name: "Eusébio",           pos: "FWD", nation: "Portugal",    flag: "🇵🇹", decade: "1960s", club: "Benfica",         ovr: 89, pwr: 90 },
  { id: "garrincha",    name: "Garrincha",         pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "1960s", club: "Botafogo",        ovr: 89, pwr: 89 },
  { id: "seeler",       name: "Uwe Seeler",        pos: "FWD", nation: "Germany",     flag: "🇩🇪", decade: "1960s", club: "Hamburg",         ovr: 83, pwr: 84 },
  { id: "greaves",      name: "Jimmy Greaves",     pos: "FWD", nation: "England",     flag: "🏴",  decade: "1960s", club: "Tottenham",       ovr: 84, pwr: 85 },
  { id: "muller",       name: "Gerd Müller",       pos: "FWD", nation: "Germany",     flag: "🇩🇪", decade: "1970s", club: "Bayern Munich",   ovr: 90, pwr: 92 },
  { id: "cruyff",       name: "Johan Cruyff",      pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "1970s", club: "Ajax",            ovr: 93, pwr: 92 },
  { id: "best",         name: "George Best",       pos: "FWD", nation: "N. Ireland",  flag: "🇬🇧", decade: "1970s", club: "Man United",      ovr: 88, pwr: 88 },
  { id: "riva",         name: "Gigi Riva",         pos: "FWD", nation: "Italy",       flag: "🇮🇹", decade: "1970s", club: "Cagliari",        ovr: 85, pwr: 86 },
  { id: "kempes",       name: "Mario Kempes",      pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "1970s", club: "Valencia",        ovr: 85, pwr: 85 },
  { id: "rivelino",     name: "Rivelino",          pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "1970s", club: "Corinthians",     ovr: 85, pwr: 85 },
  { id: "vanbasten",    name: "Marco van Basten",  pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "1980s", club: "AC Milan",        ovr: 90, pwr: 91 },
  { id: "rummenigge",   name: "Karl-Heinz Rummenigge",pos:"FWD",nation: "Germany",    flag: "🇩🇪", decade: "1980s", club: "Bayern Munich",   ovr: 86, pwr: 87 },
  { id: "rossi",        name: "Paolo Rossi",       pos: "FWD", nation: "Italy",       flag: "🇮🇹", decade: "1980s", club: "Juventus",        ovr: 84, pwr: 85 },
  { id: "butragueno",   name: "Emilio Butragueño", pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "1980s", club: "Real Madrid",     ovr: 82, pwr: 82 },
  { id: "lineker",      name: "Gary Lineker",      pos: "FWD", nation: "England",     flag: "🏴",  decade: "1980s", club: "Tottenham",       ovr: 85, pwr: 85 },
  { id: "maradona",     name: "Diego Maradona",    pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "1980s", club: "Napoli",          ovr: 94, pwr: 93 },
  { id: "romario",      name: "Romário",           pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "1990s", club: "Barcelona",       ovr: 88, pwr: 90 },
  { id: "batistuta",    name: "Gabriel Batistuta", pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "1990s", club: "Fiorentina",      ovr: 86, pwr: 88 },
  { id: "klinsmann",    name: "Jürgen Klinsmann",  pos: "FWD", nation: "Germany",     flag: "🇩🇪", decade: "1990s", club: "Tottenham",       ovr: 85, pwr: 86 },
  { id: "papin",        name: "Jean-Pierre Papin", pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "1990s", club: "Marseille",       ovr: 84, pwr: 85 },
  { id: "shearer",      name: "Alan Shearer",      pos: "FWD", nation: "England",     flag: "🏴",  decade: "1990s", club: "Newcastle",       ovr: 85, pwr: 86 },
  { id: "bergkamp",     name: "Dennis Bergkamp",   pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "1990s", club: "Arsenal",         ovr: 87, pwr: 87 },
  { id: "ronaldo",      name: "Ronaldo Nazário",   pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "Real Madrid",     ovr: 92, pwr: 93 },
  { id: "ronaldinho",   name: "Ronaldinho",        pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "2000s", club: "Barcelona",       ovr: 90, pwr: 90 },
  { id: "henry",        name: "Thierry Henry",     pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Arsenal",         ovr: 88, pwr: 89 },
  { id: "trezeguet",    name: "David Trezeguet",   pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2000s", club: "Juventus",        ovr: 83, pwr: 84 },
  { id: "klose",        name: "Miroslav Klose",    pos: "FWD", nation: "Germany",     flag: "🇩🇪", decade: "2000s", club: "Bayern Munich",   ovr: 84, pwr: 85 },
  { id: "delpiero",     name: "Alessandro Del Piero",pos:"FWD",nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "Juventus",        ovr: 86, pwr: 86 },
  { id: "totti",        name: "Francesco Totti",   pos: "FWD", nation: "Italy",       flag: "🇮🇹", decade: "2000s", club: "AS Roma",         ovr: 86, pwr: 86 },
  { id: "raul",         name: "Raúl",              pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Real Madrid",     ovr: 86, pwr: 86 },
  { id: "torres",       name: "Fernando Torres",   pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Liverpool",       ovr: 84, pwr: 84 },
  { id: "morientes",    name: "Fernando Morientes",pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "2000s", club: "Real Madrid",     ovr: 81, pwr: 81 },
  { id: "owen",         name: "Michael Owen",      pos: "FWD", nation: "England",     flag: "🏴",  decade: "2000s", club: "Liverpool",       ovr: 83, pwr: 84 },
  { id: "vannistelrooy",name: "Ruud van Nistelrooy",pos:"FWD", nation: "Netherlands", flag: "🇳🇱", decade: "2000s", club: "Man United",      ovr: 84, pwr: 85 },
  { id: "messi",        name: "Lionel Messi",      pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "2010s", club: "Barcelona",       ovr: 95, pwr: 95 },
  { id: "cristiano",    name: "Cristiano Ronaldo", pos: "FWD", nation: "Portugal",    flag: "🇵🇹", decade: "2010s", club: "Real Madrid",     ovr: 93, pwr: 93 },
  { id: "ibrahimovic",  name: "Zlatan Ibrahimović",pos: "FWD", nation: "Sweden",      flag: "🇸🇪", decade: "2010s", club: "Milan / PSG",     ovr: 88, pwr: 88 },
  { id: "benzema",      name: "Karim Benzema",     pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Real Madrid",     ovr: 86, pwr: 87 },
  { id: "griezmann",    name: "Antoine Griezmann", pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2010s", club: "Atlético Madrid", ovr: 84, pwr: 84 },
  { id: "villa",        name: "David Villa",       pos: "FWD", nation: "Spain",       flag: "🇪🇸", decade: "2010s", club: "Barcelona",       ovr: 84, pwr: 85 },
  { id: "rooney",       name: "Wayne Rooney",      pos: "FWD", nation: "England",     flag: "🏴",  decade: "2010s", club: "Man United",      ovr: 85, pwr: 85 },
  { id: "robben",       name: "Arjen Robben",      pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "2010s", club: "Bayern Munich",   ovr: 85, pwr: 85 },
  { id: "vanpersie",    name: "Robin van Persie",  pos: "FWD", nation: "Netherlands", flag: "🇳🇱", decade: "2010s", club: "Man United",      ovr: 84, pwr: 85 },
  { id: "aguero",       name: "Sergio Agüero",     pos: "FWD", nation: "Argentina",   flag: "🇦🇷", decade: "2010s", club: "Man City",        ovr: 85, pwr: 86 },
  { id: "neymar",       name: "Neymar",            pos: "FWD", nation: "Brazil",      flag: "🇧🇷", decade: "2010s", club: "Barcelona / PSG", ovr: 86, pwr: 87 },
  { id: "mbappe",       name: "Kylian Mbappé",     pos: "FWD", nation: "France",      flag: "🇫🇷", decade: "2020s", club: "Paris SG",        ovr: 91, pwr: 92 },
  { id: "lewandowski",  name: "Robert Lewandowski",pos: "FWD", nation: "Poland",      flag: "🇵🇱", decade: "2020s", club: "Bayern Munich",   ovr: 90, pwr: 91 },
  { id: "kane",         name: "Harry Kane",        pos: "FWD", nation: "England",     flag: "🏴",  decade: "2020s", club: "Bayern Munich",   ovr: 85, pwr: 86 },

  // ===================================================================
  // EXPANSION — more nations & confederations
  // Grouped by nation. Confederation is derived from nation in js/modes.js,
  // so no extra field is needed here. These unlock Nation mode for new
  // countries and power the continental (By Region) modes.
  // ===================================================================

  // -------- Uruguay (CONMEBOL) --------
  { id: "uru_muslera",      name: "Fernando Muslera",   pos: "GK",  nation: "Uruguay", flag: "🇺🇾", decade: "2010s", club: "Galatasaray",      ovr: 81, pwr: 81 },
  { id: "uru_mazurkiewicz", name: "Ladislao Mazurkiewicz", pos: "GK", nation: "Uruguay", flag: "🇺🇾", decade: "1970s", club: "Peñarol",       ovr: 80, pwr: 80 },
  { id: "uru_godin",        name: "Diego Godín",        pos: "DEF", nation: "Uruguay", flag: "🇺🇾", decade: "2010s", club: "Atlético Madrid",  ovr: 85, pwr: 85 },
  { id: "uru_montero",      name: "Paolo Montero",      pos: "DEF", nation: "Uruguay", flag: "🇺🇾", decade: "1990s", club: "Juventus",         ovr: 82, pwr: 82 },
  { id: "uru_santamaria",   name: "José Santamaría",    pos: "DEF", nation: "Uruguay", flag: "🇺🇾", decade: "1960s", club: "Real Madrid",      ovr: 83, pwr: 83 },
  { id: "uru_lugano",       name: "Diego Lugano",       pos: "DEF", nation: "Uruguay", flag: "🇺🇾", decade: "2000s", club: "Fenerbahçe",       ovr: 80, pwr: 80 },
  { id: "uru_caceres",      name: "Martín Cáceres",     pos: "DEF", nation: "Uruguay", flag: "🇺🇾", decade: "2010s", club: "Juventus",         ovr: 78, pwr: 78 },
  { id: "uru_francescoli",  name: "Enzo Francescoli",   pos: "MID", nation: "Uruguay", flag: "🇺🇾", decade: "1990s", club: "River Plate",      ovr: 85, pwr: 85 },
  { id: "uru_valverde",     name: "Federico Valverde",  pos: "MID", nation: "Uruguay", flag: "🇺🇾", decade: "2020s", club: "Real Madrid",      ovr: 84, pwr: 84 },
  { id: "uru_recoba",       name: "Álvaro Recoba",      pos: "MID", nation: "Uruguay", flag: "🇺🇾", decade: "2000s", club: "Inter Milan",      ovr: 80, pwr: 80 },
  { id: "uru_suarez",       name: "Luis Suárez",        pos: "FWD", nation: "Uruguay", flag: "🇺🇾", decade: "2010s", club: "Barcelona",        ovr: 88, pwr: 89 },
  { id: "uru_cavani",       name: "Edinson Cavani",     pos: "FWD", nation: "Uruguay", flag: "🇺🇾", decade: "2010s", club: "Paris SG",         ovr: 84, pwr: 85 },
  { id: "uru_forlan",       name: "Diego Forlán",       pos: "FWD", nation: "Uruguay", flag: "🇺🇾", decade: "2010s", club: "Atlético Madrid",  ovr: 84, pwr: 85 },

  // -------- Colombia (CONMEBOL) --------
  { id: "col_higuita",      name: "René Higuita",       pos: "GK",  nation: "Colombia", flag: "🇨🇴", decade: "1990s", club: "Atlético Nacional", ovr: 81, pwr: 81 },
  { id: "col_cordoba_o",    name: "Óscar Córdoba",      pos: "GK",  nation: "Colombia", flag: "🇨🇴", decade: "1990s", club: "Boca Juniors",     ovr: 80, pwr: 80 },
  { id: "col_ivancordoba",  name: "Iván Córdoba",       pos: "DEF", nation: "Colombia", flag: "🇨🇴", decade: "2000s", club: "Inter Milan",      ovr: 81, pwr: 81 },
  { id: "col_yepes",        name: "Mario Yepes",        pos: "DEF", nation: "Colombia", flag: "🇨🇴", decade: "2000s", club: "AC Milan",         ovr: 80, pwr: 80 },
  { id: "col_escobar",      name: "Andrés Escobar",     pos: "DEF", nation: "Colombia", flag: "🇨🇴", decade: "1990s", club: "Atlético Nacional", ovr: 79, pwr: 79 },
  { id: "col_davinson",     name: "Dávinson Sánchez",   pos: "DEF", nation: "Colombia", flag: "🇨🇴", decade: "2020s", club: "Tottenham",        ovr: 78, pwr: 78 },
  { id: "col_valderrama",   name: "Carlos Valderrama",  pos: "MID", nation: "Colombia", flag: "🇨🇴", decade: "1990s", club: "Junior",           ovr: 85, pwr: 85 },
  { id: "col_james",        name: "James Rodríguez",    pos: "MID", nation: "Colombia", flag: "🇨🇴", decade: "2010s", club: "Real Madrid",      ovr: 83, pwr: 83 },
  { id: "col_rincon",       name: "Freddy Rincón",      pos: "MID", nation: "Colombia", flag: "🇨🇴", decade: "1990s", club: "Real Madrid",      ovr: 80, pwr: 80 },
  { id: "col_falcao",       name: "Radamel Falcao",     pos: "FWD", nation: "Colombia", flag: "🇨🇴", decade: "2010s", club: "Atlético Madrid",  ovr: 84, pwr: 85 },
  { id: "col_asprilla",     name: "Faustino Asprilla",  pos: "FWD", nation: "Colombia", flag: "🇨🇴", decade: "1990s", club: "Parma",            ovr: 81, pwr: 81 },
  { id: "col_luisdiaz",     name: "Luis Díaz",          pos: "FWD", nation: "Colombia", flag: "🇨🇴", decade: "2020s", club: "Liverpool",        ovr: 82, pwr: 82 },

  // -------- Chile (CONMEBOL) --------
  { id: "chi_bravo",        name: "Claudio Bravo",      pos: "GK",  nation: "Chile",   flag: "🇨🇱", decade: "2010s", club: "Barcelona",        ovr: 81, pwr: 81 },
  { id: "chi_figueroa",     name: "Elías Figueroa",     pos: "DEF", nation: "Chile",   flag: "🇨🇱", decade: "1970s", club: "Internacional",    ovr: 84, pwr: 84 },
  { id: "chi_medel",        name: "Gary Medel",         pos: "DEF", nation: "Chile",   flag: "🇨🇱", decade: "2010s", club: "Bologna",          ovr: 79, pwr: 79 },
  { id: "chi_isla",         name: "Mauricio Isla",      pos: "DEF", nation: "Chile",   flag: "🇨🇱", decade: "2010s", club: "Juventus",         ovr: 77, pwr: 77 },
  { id: "chi_jara",         name: "Gonzalo Jara",       pos: "DEF", nation: "Chile",   flag: "🇨🇱", decade: "2010s", club: "West Brom",        ovr: 76, pwr: 76 },
  { id: "chi_vidal",        name: "Arturo Vidal",       pos: "MID", nation: "Chile",   flag: "🇨🇱", decade: "2010s", club: "Juventus",         ovr: 84, pwr: 84 },
  { id: "chi_valdivia",     name: "Jorge Valdivia",     pos: "MID", nation: "Chile",   flag: "🇨🇱", decade: "2010s", club: "Palmeiras",        ovr: 79, pwr: 79 },
  { id: "chi_aranguiz",     name: "Charles Aránguiz",   pos: "MID", nation: "Chile",   flag: "🇨🇱", decade: "2010s", club: "Leverkusen",       ovr: 78, pwr: 78 },
  { id: "chi_zamorano",     name: "Iván Zamorano",      pos: "FWD", nation: "Chile",   flag: "🇨🇱", decade: "1990s", club: "Real Madrid",      ovr: 83, pwr: 83 },
  { id: "chi_salas",        name: "Marcelo Salas",      pos: "FWD", nation: "Chile",   flag: "🇨🇱", decade: "1990s", club: "Lazio",            ovr: 82, pwr: 82 },
  { id: "chi_alexis",       name: "Alexis Sánchez",     pos: "FWD", nation: "Chile",   flag: "🇨🇱", decade: "2010s", club: "Arsenal",          ovr: 84, pwr: 84 },

  // -------- Nigeria (CAF) --------
  { id: "ngr_enyeama",      name: "Vincent Enyeama",    pos: "GK",  nation: "Nigeria", flag: "🇳🇬", decade: "2010s", club: "Lille",            ovr: 80, pwr: 80 },
  { id: "ngr_rufai",        name: "Peter Rufai",        pos: "GK",  nation: "Nigeria", flag: "🇳🇬", decade: "1990s", club: "Deportivo",        ovr: 76, pwr: 76 },
  { id: "ngr_west",         name: "Taribo West",        pos: "DEF", nation: "Nigeria", flag: "🇳🇬", decade: "1990s", club: "Inter Milan",      ovr: 78, pwr: 78 },
  { id: "ngr_yobo",         name: "Joseph Yobo",        pos: "DEF", nation: "Nigeria", flag: "🇳🇬", decade: "2000s", club: "Everton",          ovr: 78, pwr: 78 },
  { id: "ngr_keshi",        name: "Stephen Keshi",      pos: "DEF", nation: "Nigeria", flag: "🇳🇬", decade: "1990s", club: "Anderlecht",       ovr: 76, pwr: 76 },
  { id: "ngr_ekong",        name: "William Troost-Ekong", pos: "DEF", nation: "Nigeria", flag: "🇳🇬", decade: "2020s", club: "Udinese",       ovr: 75, pwr: 75 },
  { id: "ngr_okocha",       name: "Jay-Jay Okocha",     pos: "MID", nation: "Nigeria", flag: "🇳🇬", decade: "2000s", club: "Bolton",           ovr: 84, pwr: 84 },
  { id: "ngr_mikel",        name: "John Obi Mikel",     pos: "MID", nation: "Nigeria", flag: "🇳🇬", decade: "2010s", club: "Chelsea",          ovr: 78, pwr: 78 },
  { id: "ngr_oliseh",       name: "Sunday Oliseh",      pos: "MID", nation: "Nigeria", flag: "🇳🇬", decade: "1990s", club: "Ajax",             ovr: 78, pwr: 78 },
  { id: "ngr_kanu",         name: "Nwankwo Kanu",       pos: "FWD", nation: "Nigeria", flag: "🇳🇬", decade: "2000s", club: "Arsenal",          ovr: 81, pwr: 81 },
  { id: "ngr_yekini",       name: "Rashidi Yekini",     pos: "FWD", nation: "Nigeria", flag: "🇳🇬", decade: "1990s", club: "Vitória",          ovr: 80, pwr: 80 },
  { id: "ngr_osimhen",      name: "Victor Osimhen",     pos: "FWD", nation: "Nigeria", flag: "🇳🇬", decade: "2020s", club: "Napoli",           ovr: 83, pwr: 83 },

  // -------- Cameroon (CAF) --------
  { id: "cmr_nkono",        name: "Thomas N'Kono",      pos: "GK",  nation: "Cameroon", flag: "🇨🇲", decade: "1980s", club: "Espanyol",        ovr: 80, pwr: 80 },
  { id: "cmr_bell",         name: "Joseph-Antoine Bell", pos: "GK", nation: "Cameroon", flag: "🇨🇲", decade: "1990s", club: "Marseille",       ovr: 76, pwr: 76 },
  { id: "cmr_matip",        name: "Joël Matip",         pos: "DEF", nation: "Cameroon", flag: "🇨🇲", decade: "2010s", club: "Liverpool",       ovr: 80, pwr: 80 },
  { id: "cmr_song",         name: "Rigobert Song",      pos: "DEF", nation: "Cameroon", flag: "🇨🇲", decade: "2000s", club: "Liverpool",       ovr: 77, pwr: 77 },
  { id: "cmr_nkoulou",      name: "Nicolas N'Koulou",   pos: "DEF", nation: "Cameroon", flag: "🇨🇲", decade: "2010s", club: "Torino",          ovr: 77, pwr: 77 },
  { id: "cmr_wome",         name: "Pierre Womé",        pos: "DEF", nation: "Cameroon", flag: "🇨🇲", decade: "2000s", club: "Inter Milan",     ovr: 75, pwr: 75 },
  { id: "cmr_foe",          name: "Marc-Vivien Foé",    pos: "MID", nation: "Cameroon", flag: "🇨🇲", decade: "2000s", club: "Lyon",            ovr: 78, pwr: 78 },
  { id: "cmr_geremi",       name: "Geremi",             pos: "MID", nation: "Cameroon", flag: "🇨🇲", decade: "2000s", club: "Chelsea",         ovr: 78, pwr: 78 },
  { id: "cmr_makoun",       name: "Jean Makoun",        pos: "MID", nation: "Cameroon", flag: "🇨🇲", decade: "2000s", club: "Lyon",            ovr: 76, pwr: 76 },
  { id: "cmr_etoo",         name: "Samuel Eto'o",       pos: "FWD", nation: "Cameroon", flag: "🇨🇲", decade: "2000s", club: "Barcelona",       ovr: 86, pwr: 86 },
  { id: "cmr_milla",        name: "Roger Milla",        pos: "FWD", nation: "Cameroon", flag: "🇨🇲", decade: "1990s", club: "Montpellier",     ovr: 82, pwr: 82 },
  { id: "cmr_mboma",        name: "Patrick Mboma",      pos: "FWD", nation: "Cameroon", flag: "🇨🇲", decade: "2000s", club: "Parma",           ovr: 79, pwr: 79 },

  // -------- Other African greats (CAF depth) --------
  { id: "lbr_weah",         name: "George Weah",        pos: "FWD", nation: "Liberia",     flag: "🇱🇷", decade: "1990s", club: "AC Milan",     ovr: 86, pwr: 86 },
  { id: "civ_drogba",       name: "Didier Drogba",      pos: "FWD", nation: "Ivory Coast", flag: "🇨🇮", decade: "2000s", club: "Chelsea",      ovr: 85, pwr: 86 },
  { id: "civ_yayatoure",    name: "Yaya Touré",         pos: "MID", nation: "Ivory Coast", flag: "🇨🇮", decade: "2010s", club: "Man City",     ovr: 85, pwr: 85 },
  { id: "civ_kolotoure",    name: "Kolo Touré",         pos: "DEF", nation: "Ivory Coast", flag: "🇨🇮", decade: "2000s", club: "Arsenal",      ovr: 79, pwr: 79 },
  { id: "egy_salah",        name: "Mohamed Salah",      pos: "FWD", nation: "Egypt",       flag: "🇪🇬", decade: "2020s", club: "Liverpool",    ovr: 88, pwr: 88 },
  { id: "egy_aboutrika",    name: "Mohamed Aboutrika",  pos: "MID", nation: "Egypt",       flag: "🇪🇬", decade: "2000s", club: "Al Ahly",      ovr: 80, pwr: 80 },
  { id: "egy_elhadary",     name: "Essam El-Hadary",    pos: "GK",  nation: "Egypt",       flag: "🇪🇬", decade: "2000s", club: "Al Ahly",      ovr: 78, pwr: 78 },
  { id: "sen_mane",         name: "Sadio Mané",         pos: "FWD", nation: "Senegal",     flag: "🇸🇳", decade: "2020s", club: "Liverpool",    ovr: 85, pwr: 85 },
  { id: "sen_koulibaly",    name: "Kalidou Koulibaly",  pos: "DEF", nation: "Senegal",     flag: "🇸🇳", decade: "2020s", club: "Napoli",       ovr: 82, pwr: 82 },
  { id: "sen_mendy",        name: "Édouard Mendy",      pos: "GK",  nation: "Senegal",     flag: "🇸🇳", decade: "2020s", club: "Chelsea",      ovr: 80, pwr: 80 },
  { id: "sen_diouf",        name: "El Hadji Diouf",     pos: "FWD", nation: "Senegal",     flag: "🇸🇳", decade: "2000s", club: "Liverpool",    ovr: 79, pwr: 79 },
  { id: "gha_essien",       name: "Michael Essien",     pos: "MID", nation: "Ghana",       flag: "🇬🇭", decade: "2000s", club: "Chelsea",      ovr: 82, pwr: 82 },
  { id: "gha_abedi",        name: "Abedi Pelé",         pos: "MID", nation: "Ghana",       flag: "🇬🇭", decade: "1990s", club: "Marseille",    ovr: 82, pwr: 82 },
  { id: "gha_gyan",         name: "Asamoah Gyan",       pos: "FWD", nation: "Ghana",       flag: "🇬🇭", decade: "2010s", club: "Sunderland",   ovr: 79, pwr: 79 },
  { id: "alg_mahrez",       name: "Riyad Mahrez",       pos: "FWD", nation: "Algeria",     flag: "🇩🇿", decade: "2010s", club: "Man City",     ovr: 83, pwr: 83 },
  { id: "alg_madjer",       name: "Rabah Madjer",       pos: "FWD", nation: "Algeria",     flag: "🇩🇿", decade: "1980s", club: "FC Porto",     ovr: 80, pwr: 80 },
  { id: "mar_hakimi",       name: "Achraf Hakimi",      pos: "DEF", nation: "Morocco",     flag: "🇲🇦", decade: "2020s", club: "Paris SG",     ovr: 83, pwr: 83 },
  { id: "mar_ziyech",       name: "Hakim Ziyech",       pos: "MID", nation: "Morocco",     flag: "🇲🇦", decade: "2020s", club: "Chelsea",      ovr: 80, pwr: 80 },
  { id: "mar_bounou",       name: "Yassine Bounou",     pos: "GK",  nation: "Morocco",     flag: "🇲🇦", decade: "2020s", club: "Sevilla",      ovr: 80, pwr: 80 },

  // -------- Mexico (CONCACAF) --------
  { id: "mex_ochoa",        name: "Guillermo Ochoa",    pos: "GK",  nation: "Mexico",  flag: "🇲🇽", decade: "2010s", club: "Club América",     ovr: 79, pwr: 79 },
  { id: "mex_campos",       name: "Jorge Campos",       pos: "GK",  nation: "Mexico",  flag: "🇲🇽", decade: "1990s", club: "Pumas",            ovr: 79, pwr: 79 },
  { id: "mex_marquez",      name: "Rafael Márquez",     pos: "DEF", nation: "Mexico",  flag: "🇲🇽", decade: "2000s", club: "Barcelona",        ovr: 83, pwr: 83 },
  { id: "mex_claudiosuarez", name: "Claudio Suárez",    pos: "DEF", nation: "Mexico",  flag: "🇲🇽", decade: "1990s", club: "Chivas",           ovr: 79, pwr: 79 },
  { id: "mex_salcido",      name: "Carlos Salcido",     pos: "DEF", nation: "Mexico",  flag: "🇲🇽", decade: "2000s", club: "PSV Eindhoven",    ovr: 78, pwr: 78 },
  { id: "mex_moreno",       name: "Héctor Moreno",      pos: "DEF", nation: "Mexico",  flag: "🇲🇽", decade: "2010s", club: "Espanyol",         ovr: 77, pwr: 77 },
  { id: "mex_blanco",       name: "Cuauhtémoc Blanco",  pos: "MID", nation: "Mexico",  flag: "🇲🇽", decade: "2000s", club: "Club América",     ovr: 80, pwr: 80 },
  { id: "mex_guardado",     name: "Andrés Guardado",    pos: "MID", nation: "Mexico",  flag: "🇲🇽", decade: "2010s", club: "Real Betis",       ovr: 79, pwr: 79 },
  { id: "mex_pardo",        name: "Pavel Pardo",        pos: "MID", nation: "Mexico",  flag: "🇲🇽", decade: "2000s", club: "VfB Stuttgart",    ovr: 77, pwr: 77 },
  { id: "mex_hugosanchez",  name: "Hugo Sánchez",       pos: "FWD", nation: "Mexico",  flag: "🇲🇽", decade: "1980s", club: "Real Madrid",      ovr: 86, pwr: 86 },
  { id: "mex_chicharito",   name: "Javier Hernández",   pos: "FWD", nation: "Mexico",  flag: "🇲🇽", decade: "2010s", club: "Man United",       ovr: 80, pwr: 80 },
  { id: "mex_borgetti",     name: "Jared Borgetti",     pos: "FWD", nation: "Mexico",  flag: "🇲🇽", decade: "2000s", club: "Pachuca",          ovr: 79, pwr: 79 },

  // -------- USA (CONCACAF) --------
  { id: "usa_howard",       name: "Tim Howard",         pos: "GK",  nation: "USA",     flag: "🇺🇸", decade: "2010s", club: "Everton",          ovr: 80, pwr: 80 },
  { id: "usa_friedel",      name: "Brad Friedel",       pos: "GK",  nation: "USA",     flag: "🇺🇸", decade: "2000s", club: "Blackburn",        ovr: 78, pwr: 78 },
  { id: "usa_bocanegra",    name: "Carlos Bocanegra",   pos: "DEF", nation: "USA",     flag: "🇺🇸", decade: "2000s", club: "Fulham",           ovr: 77, pwr: 77 },
  { id: "usa_pope",         name: "Eddie Pope",         pos: "DEF", nation: "USA",     flag: "🇺🇸", decade: "2000s", club: "DC United",        ovr: 76, pwr: 76 },
  { id: "usa_beasley",      name: "DaMarcus Beasley",   pos: "DEF", nation: "USA",     flag: "🇺🇸", decade: "2000s", club: "PSV Eindhoven",    ovr: 76, pwr: 76 },
  { id: "usa_cherundolo",   name: "Steve Cherundolo",   pos: "DEF", nation: "USA",     flag: "🇺🇸", decade: "2000s", club: "Hannover",         ovr: 75, pwr: 75 },
  { id: "usa_reyna",        name: "Claudio Reyna",      pos: "MID", nation: "USA",     flag: "🇺🇸", decade: "2000s", club: "Rangers",          ovr: 78, pwr: 78 },
  { id: "usa_bradley",      name: "Michael Bradley",    pos: "MID", nation: "USA",     flag: "🇺🇸", decade: "2010s", club: "AS Roma",          ovr: 77, pwr: 77 },
  { id: "usa_pulisic",      name: "Christian Pulisic",  pos: "MID", nation: "USA",     flag: "🇺🇸", decade: "2020s", club: "AC Milan",         ovr: 81, pwr: 81 },
  { id: "usa_donovan",      name: "Landon Donovan",     pos: "FWD", nation: "USA",     flag: "🇺🇸", decade: "2000s", club: "LA Galaxy",        ovr: 81, pwr: 81 },
  { id: "usa_dempsey",      name: "Clint Dempsey",      pos: "FWD", nation: "USA",     flag: "🇺🇸", decade: "2010s", club: "Fulham",           ovr: 80, pwr: 80 },
  { id: "usa_mcbride",      name: "Brian McBride",      pos: "FWD", nation: "USA",     flag: "🇺🇸", decade: "2000s", club: "Fulham",           ovr: 76, pwr: 76 },

  // -------- Costa Rica (CONCACAF depth) --------
  { id: "crc_navas",        name: "Keylor Navas",       pos: "GK",  nation: "Costa Rica", flag: "🇨🇷", decade: "2010s", club: "Real Madrid",   ovr: 82, pwr: 82 },
  { id: "crc_wanchope",     name: "Paulo Wanchope",     pos: "FWD", nation: "Costa Rica", flag: "🇨🇷", decade: "2000s", club: "Man City",      ovr: 78, pwr: 78 },
  { id: "crc_ruiz",         name: "Bryan Ruiz",         pos: "MID", nation: "Costa Rica", flag: "🇨🇷", decade: "2010s", club: "Fulham",        ovr: 76, pwr: 76 },

  // -------- Japan (AFC) --------
  { id: "jpn_kawaguchi",    name: "Yoshikatsu Kawaguchi", pos: "GK", nation: "Japan",  flag: "🇯🇵", decade: "2000s", club: "Júbilo Iwata",     ovr: 78, pwr: 78 },
  { id: "jpn_kawashima",    name: "Eiji Kawashima",     pos: "GK",  nation: "Japan",   flag: "🇯🇵", decade: "2010s", club: "Standard Liège",   ovr: 76, pwr: 76 },
  { id: "jpn_nagatomo",     name: "Yuto Nagatomo",      pos: "DEF", nation: "Japan",   flag: "🇯🇵", decade: "2010s", club: "Inter Milan",      ovr: 77, pwr: 77 },
  { id: "jpn_yoshida",      name: "Maya Yoshida",       pos: "DEF", nation: "Japan",   flag: "🇯🇵", decade: "2010s", club: "Southampton",      ovr: 77, pwr: 77 },
  { id: "jpn_tomiyasu",     name: "Takehiro Tomiyasu",  pos: "DEF", nation: "Japan",   flag: "🇯🇵", decade: "2020s", club: "Arsenal",          ovr: 78, pwr: 78 },
  { id: "jpn_nakazawa",     name: "Yuji Nakazawa",      pos: "DEF", nation: "Japan",   flag: "🇯🇵", decade: "2000s", club: "Yokohama",         ovr: 76, pwr: 76 },
  { id: "jpn_nakata",       name: "Hidetoshi Nakata",   pos: "MID", nation: "Japan",   flag: "🇯🇵", decade: "2000s", club: "AS Roma",          ovr: 82, pwr: 82 },
  { id: "jpn_nakamura",     name: "Shunsuke Nakamura",  pos: "MID", nation: "Japan",   flag: "🇯🇵", decade: "2000s", club: "Celtic",           ovr: 80, pwr: 80 },
  { id: "jpn_honda",        name: "Keisuke Honda",      pos: "MID", nation: "Japan",   flag: "🇯🇵", decade: "2010s", club: "AC Milan",         ovr: 80, pwr: 80 },
  { id: "jpn_kagawa",       name: "Shinji Kagawa",      pos: "FWD", nation: "Japan",   flag: "🇯🇵", decade: "2010s", club: "Bor. Dortmund",    ovr: 80, pwr: 80 },
  { id: "jpn_miura",        name: "Kazuyoshi Miura",    pos: "FWD", nation: "Japan",   flag: "🇯🇵", decade: "1990s", club: "Verdy",            ovr: 78, pwr: 78 },
  { id: "jpn_minamino",     name: "Takumi Minamino",    pos: "FWD", nation: "Japan",   flag: "🇯🇵", decade: "2020s", club: "AS Monaco",        ovr: 77, pwr: 77 },

  // -------- South Korea (AFC) --------
  { id: "kor_leewoonjae",   name: "Lee Woon-jae",       pos: "GK",  nation: "South Korea", flag: "🇰🇷", decade: "2000s", club: "Suwon",        ovr: 78, pwr: 78 },
  { id: "kor_jokwon",       name: "Jo Hyeon-woo",       pos: "GK",  nation: "South Korea", flag: "🇰🇷", decade: "2020s", club: "Ulsan",        ovr: 75, pwr: 75 },
  { id: "kor_hongmyungbo",  name: "Hong Myung-bo",      pos: "DEF", nation: "South Korea", flag: "🇰🇷", decade: "2000s", club: "Pohang",       ovr: 80, pwr: 80 },
  { id: "kor_kimminjae",    name: "Kim Min-jae",        pos: "DEF", nation: "South Korea", flag: "🇰🇷", decade: "2020s", club: "Bayern Munich", ovr: 82, pwr: 82 },
  { id: "kor_leeyoungpyo",  name: "Lee Young-pyo",      pos: "DEF", nation: "South Korea", flag: "🇰🇷", decade: "2000s", club: "Tottenham",    ovr: 77, pwr: 77 },
  { id: "kor_kimyounggwon", name: "Kim Young-gwon",     pos: "DEF", nation: "South Korea", flag: "🇰🇷", decade: "2010s", club: "Guangzhou",    ovr: 75, pwr: 75 },
  { id: "kor_parkjisung",   name: "Park Ji-sung",       pos: "MID", nation: "South Korea", flag: "🇰🇷", decade: "2000s", club: "Man United",   ovr: 82, pwr: 82 },
  { id: "kor_kisungyueng",  name: "Ki Sung-yueng",      pos: "MID", nation: "South Korea", flag: "🇰🇷", decade: "2010s", club: "Swansea",      ovr: 77, pwr: 77 },
  { id: "kor_koojacheol",   name: "Koo Ja-cheol",       pos: "MID", nation: "South Korea", flag: "🇰🇷", decade: "2010s", club: "Augsburg",     ovr: 75, pwr: 75 },
  { id: "kor_chabumkun",    name: "Cha Bum-kun",        pos: "FWD", nation: "South Korea", flag: "🇰🇷", decade: "1980s", club: "Leverkusen",   ovr: 82, pwr: 82 },
  { id: "kor_son",          name: "Son Heung-min",      pos: "FWD", nation: "South Korea", flag: "🇰🇷", decade: "2020s", club: "Tottenham",    ovr: 86, pwr: 86 },
  { id: "kor_hwang",        name: "Hwang Hee-chan",     pos: "FWD", nation: "South Korea", flag: "🇰🇷", decade: "2020s", club: "Wolves",       ovr: 77, pwr: 77 },

  // -------- Iran & Australia (AFC depth) --------
  { id: "irn_daei",         name: "Ali Daei",           pos: "FWD", nation: "Iran",      flag: "🇮🇷", decade: "2000s", club: "Hertha Berlin",  ovr: 80, pwr: 80 },
  { id: "irn_karimi",       name: "Ali Karimi",         pos: "MID", nation: "Iran",      flag: "🇮🇷", decade: "2000s", club: "Bayern Munich",  ovr: 79, pwr: 79 },
  { id: "irn_mahdavikia",   name: "Mehdi Mahdavikia",   pos: "MID", nation: "Iran",      flag: "🇮🇷", decade: "2000s", club: "Hamburg",        ovr: 78, pwr: 78 },
  { id: "irn_azmoun",       name: "Sardar Azmoun",      pos: "FWD", nation: "Iran",      flag: "🇮🇷", decade: "2020s", club: "Bayer Leverkusen", ovr: 79, pwr: 79 },
  { id: "aus_schwarzer",    name: "Mark Schwarzer",     pos: "GK",  nation: "Australia", flag: "🇦🇺", decade: "2000s", club: "Fulham",         ovr: 79, pwr: 79 },
  { id: "aus_neill",        name: "Lucas Neill",        pos: "DEF", nation: "Australia", flag: "🇦🇺", decade: "2000s", club: "Blackburn",      ovr: 77, pwr: 77 },
  { id: "aus_cahill",       name: "Tim Cahill",         pos: "MID", nation: "Australia", flag: "🇦🇺", decade: "2010s", club: "Everton",        ovr: 80, pwr: 80 },
  { id: "aus_kewell",       name: "Harry Kewell",       pos: "FWD", nation: "Australia", flag: "🇦🇺", decade: "2000s", club: "Liverpool",      ovr: 81, pwr: 81 },
  { id: "aus_viduka",       name: "Mark Viduka",        pos: "FWD", nation: "Australia", flag: "🇦🇺", decade: "2000s", club: "Leeds United",   ovr: 80, pwr: 80 },

  // -------- Portugal (UEFA — top up to a full XI) --------
  { id: "por_ruipatricio",  name: "Rui Patrício",       pos: "GK",  nation: "Portugal", flag: "🇵🇹", decade: "2010s", club: "Wolves",          ovr: 80, pwr: 80 },
  { id: "por_ricardo",      name: "Ricardo",            pos: "GK",  nation: "Portugal", flag: "🇵🇹", decade: "2000s", club: "Sporting CP",     ovr: 79, pwr: 79 },
  { id: "por_carvalho",     name: "Ricardo Carvalho",   pos: "DEF", nation: "Portugal", flag: "🇵🇹", decade: "2000s", club: "Chelsea",         ovr: 83, pwr: 83 },
  { id: "por_pepe",         name: "Pepe",               pos: "DEF", nation: "Portugal", flag: "🇵🇹", decade: "2010s", club: "Real Madrid",     ovr: 82, pwr: 82 },
  { id: "por_couto",        name: "Fernando Couto",     pos: "DEF", nation: "Portugal", flag: "🇵🇹", decade: "2000s", club: "Lazio",           ovr: 80, pwr: 80 },
  { id: "por_cancelo",      name: "João Cancelo",       pos: "DEF", nation: "Portugal", flag: "🇵🇹", decade: "2020s", club: "Man City",        ovr: 82, pwr: 82 },
  { id: "por_figo",         name: "Luís Figo",          pos: "MID", nation: "Portugal", flag: "🇵🇹", decade: "2000s", club: "Real Madrid",     ovr: 87, pwr: 87 },
  { id: "por_ruicosta",     name: "Rui Costa",          pos: "MID", nation: "Portugal", flag: "🇵🇹", decade: "2000s", club: "AC Milan",        ovr: 84, pwr: 84 },
  { id: "por_deco",         name: "Deco",               pos: "MID", nation: "Portugal", flag: "🇵🇹", decade: "2000s", club: "Barcelona",       ovr: 84, pwr: 84 },
  { id: "por_pauleta",      name: "Pauleta",            pos: "FWD", nation: "Portugal", flag: "🇵🇹", decade: "2000s", club: "Paris SG",        ovr: 80, pwr: 80 },
  { id: "por_nunogomes",    name: "Nuno Gomes",         pos: "FWD", nation: "Portugal", flag: "🇵🇹", decade: "2000s", club: "Benfica",         ovr: 80, pwr: 80 },

  // -------- Belgium (UEFA — top up to a full XI) --------
  { id: "bel_courtois",     name: "Thibaut Courtois",   pos: "GK",  nation: "Belgium", flag: "🇧🇪", decade: "2020s", club: "Real Madrid",      ovr: 85, pwr: 85 },
  { id: "bel_pfaff",        name: "Jean-Marie Pfaff",   pos: "GK",  nation: "Belgium", flag: "🇧🇪", decade: "1980s", club: "Bayern Munich",    ovr: 80, pwr: 80 },
  { id: "bel_vertonghen",   name: "Jan Vertonghen",     pos: "DEF", nation: "Belgium", flag: "🇧🇪", decade: "2010s", club: "Tottenham",        ovr: 80, pwr: 80 },
  { id: "bel_alderweireld", name: "Toby Alderweireld",  pos: "DEF", nation: "Belgium", flag: "🇧🇪", decade: "2010s", club: "Tottenham",        ovr: 80, pwr: 80 },
  { id: "bel_gerets",       name: "Eric Gerets",        pos: "DEF", nation: "Belgium", flag: "🇧🇪", decade: "1980s", club: "PSV Eindhoven",    ovr: 79, pwr: 79 },
  { id: "bel_vermaelen",    name: "Thomas Vermaelen",   pos: "DEF", nation: "Belgium", flag: "🇧🇪", decade: "2010s", club: "Barcelona",        ovr: 77, pwr: 77 },
  { id: "bel_scifo",        name: "Enzo Scifo",         pos: "MID", nation: "Belgium", flag: "🇧🇪", decade: "1990s", club: "AS Monaco",        ovr: 82, pwr: 82 },
  { id: "bel_witsel",       name: "Axel Witsel",        pos: "MID", nation: "Belgium", flag: "🇧🇪", decade: "2010s", club: "Bor. Dortmund",    ovr: 79, pwr: 79 },
  { id: "bel_hazard",       name: "Eden Hazard",        pos: "FWD", nation: "Belgium", flag: "🇧🇪", decade: "2010s", club: "Chelsea",          ovr: 87, pwr: 87 },
  { id: "bel_lukaku",       name: "Romelu Lukaku",      pos: "FWD", nation: "Belgium", flag: "🇧🇪", decade: "2020s", club: "Inter Milan",      ovr: 84, pwr: 84 },
  { id: "bel_ceulemans",    name: "Jan Ceulemans",      pos: "FWD", nation: "Belgium", flag: "🇧🇪", decade: "1980s", club: "Club Brugge",      ovr: 80, pwr: 80 },

  // -------- Croatia (UEFA — top up to a full XI) --------
  { id: "cro_subasic",      name: "Danijel Subašić",    pos: "GK",  nation: "Croatia", flag: "🇭🇷", decade: "2010s", club: "AS Monaco",        ovr: 79, pwr: 79 },
  { id: "cro_pletikosa",    name: "Stipe Pletikosa",    pos: "GK",  nation: "Croatia", flag: "🇭🇷", decade: "2000s", club: "Spartak Moscow",   ovr: 76, pwr: 76 },
  { id: "cro_bilic",        name: "Slaven Bilić",       pos: "DEF", nation: "Croatia", flag: "🇭🇷", decade: "1990s", club: "West Ham",         ovr: 78, pwr: 78 },
  { id: "cro_simic",        name: "Dario Šimić",        pos: "DEF", nation: "Croatia", flag: "🇭🇷", decade: "2000s", club: "AC Milan",         ovr: 77, pwr: 77 },
  { id: "cro_corluka",      name: "Vedran Ćorluka",     pos: "DEF", nation: "Croatia", flag: "🇭🇷", decade: "2010s", club: "Tottenham",        ovr: 77, pwr: 77 },
  { id: "cro_lovren",       name: "Dejan Lovren",       pos: "DEF", nation: "Croatia", flag: "🇭🇷", decade: "2010s", club: "Liverpool",        ovr: 77, pwr: 77 },
  { id: "cro_boban",        name: "Zvonimir Boban",     pos: "MID", nation: "Croatia", flag: "🇭🇷", decade: "1990s", club: "AC Milan",         ovr: 83, pwr: 83 },
  { id: "cro_prosinecki",   name: "Robert Prosinečki",  pos: "MID", nation: "Croatia", flag: "🇭🇷", decade: "1990s", club: "Real Madrid",      ovr: 83, pwr: 83 },
  { id: "cro_rakitic",      name: "Ivan Rakitić",       pos: "MID", nation: "Croatia", flag: "🇭🇷", decade: "2010s", club: "Barcelona",        ovr: 83, pwr: 83 },
  { id: "cro_suker",        name: "Davor Šuker",        pos: "FWD", nation: "Croatia", flag: "🇭🇷", decade: "1990s", club: "Real Madrid",      ovr: 84, pwr: 84 },
  { id: "cro_mandzukic",    name: "Mario Mandžukić",    pos: "FWD", nation: "Croatia", flag: "🇭🇷", decade: "2010s", club: "Juventus",         ovr: 82, pwr: 82 },
  { id: "cro_boksic",       name: "Alen Bokšić",        pos: "FWD", nation: "Croatia", flag: "🇭🇷", decade: "1990s", club: "Lazio",            ovr: 80, pwr: 80 },
];

// Lookup helper used across the app.
window.PLAYER_BY_ID = window.PLAYERS.reduce(function (acc, p) {
  acc[p.id] = p;
  return acc;
}, {});
